In [29]:
import torch

# Torch Tensors

In [30]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [31]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [32]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [33]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [34]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [35]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [36]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [37]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [38]:
print(c.mean())

tensor(2.5833)


In [39]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [40]:
print(c.std())

tensor(1.5050)


In [41]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [42]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[ 0.4990,  0.2632, -0.5630, -0.1713],
         [ 0.5338,  0.3950,  1.2589, -0.3830],
         [ 1.5018, -0.0677, -0.5085,  1.8493]],

        [[-0.1704, -1.7296, -0.1181,  1.3479],
         [-1.4429, -0.1639, -0.2120,  0.7264],
         [-0.9521,  1.1040, -0.5173,  0.9111]]])
tensor([[ 0.4990,  0.2632, -0.5630, -0.1713,  0.5338,  0.3950,  1.2589, -0.3830,
          1.5018, -0.0677, -0.5085,  1.8493],
        [-0.1704, -1.7296, -0.1181,  1.3479, -1.4429, -0.1639, -0.2120,  0.7264,
         -0.9521,  1.1040, -0.5173,  0.9111]])
tensor([[ 0.4990,  0.2632, -0.5630, -0.1713,  0.5338

In [43]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.8688, 0.5379, 0.0081, 0.6446],
        [0.1951, 0.7820, 0.9923, 0.2634],
        [0.7686, 0.3181, 0.0050, 0.3467],
        [0.0170, 0.2843, 0.4757, 0.9829]])


In [44]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 2.1167,  0.3736, -0.5121, -0.8062],
        [-1.2815,  0.8875, -0.0860,  0.5892],
        [-2.0144,  0.7229, -0.3888,  0.3823],
        [ 0.3447, -1.6745, -0.6930,  0.6621]])
torch.float32


In [45]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([9, 6, 9, 9, 8])
torch.int64


In [46]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 7, 6],
        [7, 9, 7],
        [6, 9, 8]])


In [47]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [48]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [49]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[-0.0534,  0.3270,  0.8465,  0.2249],
        [-0.0779,  1.6897, -1.2468, -0.6540],
        [ 1.1048,  0.2806,  0.4989, -0.4965],
        [-0.9573,  0.8202, -1.1742,  0.3342]], dtype=torch.float64)


In [50]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 2.9855,  0.9115, -0.5040, -0.1616],
        [-1.0863,  1.6695,  0.9063,  0.8525],
        [-1.2458,  1.0410, -0.3838,  0.7290],
        [ 0.3616, -1.3902, -0.2172,  1.6450]])


In [51]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[ 2.9855,  0.9115, -0.5040, -0.1616],
        [-1.0863,  1.6695,  0.9063,  0.8525],
        [-1.2458,  1.0410, -0.3838,  0.7290],
        [ 0.3616, -1.3902, -0.2172,  1.6450]])


In [52]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([ 0.9115,  1.6695,  1.0410, -1.3902])
tensor([[ 2.9855,  0.9115],
        [-1.0863,  1.6695],
        [-1.2458,  1.0410],
        [ 0.3616, -1.3902]])
tensor([[ 2.9855,  0.9115, -0.5040, -0.1616],
        [-1.0863,  1.6695,  0.9063,  0.8525],
        [-1.2458,  1.0410, -0.3838,  0.7290]])
tensor(0.7290)
0.7289878129959106
tensor([-1.2458,  1.0410, -0.3838,  0.7290])


## Numpy Bridge

In [53]:
import numpy as np

In [54]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [55]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [56]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

False


In [57]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [58]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [59]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 1.3735,  0.4207,  1.3821,  1.3278,  0.6720],
        [-0.4375,  0.1995,  1.0774, -0.8551,  0.3861]])
tensor([[ 1.1685,  2.1311, -1.5031, -0.8255,  0.2377],
        [ 0.0870,  1.0115,  0.5970, -0.3262,  0.2733],
        [-1.7931, -0.0388,  0.4524, -0.9827,  1.8838]])


tensor([[ 1.3735,  0.4207,  1.3821,  1.3278,  0.6720],
        [-0.4375,  0.1995,  1.0774, -0.8551,  0.3861],
        [ 1.1685,  2.1311, -1.5031, -0.8255,  0.2377],
        [ 0.0870,  1.0115,  0.5970, -0.3262,  0.2733],
        [-1.7931, -0.0388,  0.4524, -0.9827,  1.8838]])


tensor([[ 0.8735,  0.0602,  0.2449],
        [-0.4850,  0.0615, -0.8479]])
tensor([[ 0.2930,  1.2678,  0.8695,  0.0361,  0.0665],
        [-1.7576,  1.6905,  1.1337,  0.0912, -1.3377]])


tensor([[ 0.8735,  0.0602,  0.2449,  0.2930,  1.2678,  0.8695,  0.0361,  0.0665],
        [-0.4850,  0.0615, -0.8479, -1.7576,  1.6905,  1.1337,  0.0912, -1.3377]])




## Adding Dimensions to Tensors

In [60]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.6352, 0.6104, 0.9255, 0.7134],
         [0.8086, 0.4518, 0.8198, 0.6110],
         [0.2862, 0.0468, 0.5402, 0.1885]],

        [[0.8767, 0.0072, 0.5258, 0.8800],
         [0.0277, 0.9803, 0.6791, 0.9334],
         [0.7125, 0.9782, 0.3342, 0.3877]]])


tensor([[0.9255, 0.8198, 0.5402],
        [0.5258, 0.6791, 0.3342]])
torch.Size([2, 3])


tensor([[[0.9255],
         [0.8198],
         [0.5402]],

        [[0.5258],
         [0.6791],
         [0.3342]]])
torch.Size([2, 3, 1])


## AutoGrad

In [61]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [62]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [63]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [64]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [65]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
