## Word Embeddings

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
#The indices of the words represent the values in the lookup table
word_to_idx = {"I": 0, "love": 1, "eating":2, "and":3, "sleeping":4}
embeddings = nn.Embedding(5, 7)    # 5 words in vocab, embedding size is 7
word_index = torch.tensor([word_to_idx["love"]])
print(word_index)

tensor([1])


In [4]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[ 1.4711, -0.0111, -0.2369,  1.4549,  1.3532,  1.3909,  0.1836]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [5]:
all_ind = torch.tensor([w for w in range(5)], dtype = torch.long)
all_words = embeddings(all_ind)
print(all_ind)
print(all_words)
print(all_words.shape)

tensor([0, 1, 2, 3, 4])
tensor([[ 2.0565, -1.5283,  0.3837, -0.2614, -0.1557,  0.4281, -1.8800],
        [ 1.4711, -0.0111, -0.2369,  1.4549,  1.3532,  1.3909,  0.1836],
        [ 1.0715,  0.4788, -0.2818,  0.2587, -0.0501, -1.9553, -0.7337],
        [ 1.0226, -0.0586, -1.0999, -0.6388, -0.4510,  1.3005,  1.3336],
        [ 0.4154, -0.6668,  1.1787,  0.2404,  0.2139,  0.9451,  1.0018]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])


## Exercise: N-Gram Skip Model
### Given a sequence of words, we want to predict the ith word of the sequence: P(w(i)|w(i-1), w(i-2), .....)
#### Source: https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html#an-example-n-gram-language-modeling  
